### ISSUE TITLE
Can't copy paste from output…

### ISSUE THREAD

**Issue by bwinton** [nathanjohnson320/run-command2#8]
Perhaps this is a documentation bug, but I can't seem to find out how to copy the output into my editor buffer…

Thanks!

**Comment by nathanjohnson320** [comment]
Hmmm I think they pushed an update that makes it so you can't copy paste from the mini buffer. I'll look into it shortly.

**Comment by bwinton** [comment]
Awesome!  (I would be even happier if there was a way to just paste the output straight into the editor pane.  Obviously as a separate command… :smile:)

**Comment by nathanjohnson320** [comment]
Oooo so a separate binding to insert the output text into the current editor position? That might be useful

**Comment by bwinton** [comment]
Yeah, maybe replacing the currently selected text, too?  (I'm not sure what that would do with multiple selections/cursors…  Maybe just use the first one to keep it simple…)

**Comment by nathanjohnson320** [comment]
So a while back I had to fix this issue here: https://discuss.atom.io/t/cant-select-panel-text/15453
But apparently that fix doesn't work anymore so I'm going to add another key binding to call atom.clipboard.write(output) which will put the output of the buffer into the clipboard. This isn't super ideal since most people want to copy paste specific lines but it's the best I can do for now.
